-- Migration: seed_automation_tools
-- Description: Inserts n8n and Zapier webhooks as configurable integrations in the global catalog.

-- Ensure the 'Developer Tools' category exists first, or fall back to general category
DO $$
DECLARE
    v_type_id uuid;
    v_category_id uuid;
BEGIN
    SELECT id INTO v_type_id FROM public.tool_types WHERE slug = 'webhook' LIMIT 1;
    IF NOT FOUND THEN
        SELECT id INTO v_type_id FROM public.tool_types LIMIT 1;
    END IF;

    SELECT id INTO v_category_id FROM public.tool_categories WHERE slug = 'developer-tools' LIMIT 1;
    IF NOT FOUND THEN
        SELECT id INTO v_category_id FROM public.tool_categories LIMIT 1;
    END IF;

    -- Insert n8n Webhook
    IF NOT EXISTS (SELECT 1 FROM public.global_tools WHERE name = 'n8n Webhook') THEN
        INSERT INTO public.global_tools (name, description, logo_icon, config_schema, type_id, category_id, is_active)
        VALUES (
            'n8n Webhook',
            'Trigger any n8n automation workflow via an HTTP Webhook. The AI Agent will dynamically generate the JSON payload sent to your n8n Catch Hook based on its current execution context.',
            'Webhook', -- Lucide icon
            '{
                "type": "object",
                "required": ["webhook_url"],
                "properties": {
                    "webhook_url": {
                        "type": "string",
                        "title": "n8n Webhook URL",
                        "description": "The exact POST URL generated by your n8n Webhook trigger node (e.g. https://your-n8n.com/webhook/1234)"
                    }
                }
            }'::jsonb,
            v_type_id,
            v_category_id,
            true
        );
    END IF;

    -- Insert Zapier Webhook
    IF NOT EXISTS (SELECT 1 FROM public.global_tools WHERE name = 'Zapier Catch Hook') THEN
        INSERT INTO public.global_tools (name, description, logo_icon, config_schema, type_id, category_id, is_active)
        VALUES (
            'Zapier Catch Hook',
            'Trigger any Zap via a Zapier Webhooks Catch Hook. The Tessera OS Agent will synthesize the necessary data array and POST it directly to Zapier to kick off your rigid automations.',
            'Zap', -- Lucide icon
            '{
                "type": "object",
                "required": ["webhook_url"],
                "properties": {
                    "webhook_url": {
                        "type": "string",
                        "title": "Zapier Webhook URL",
                        "description": "The custom Catch Hook URL generated in Zapier (e.g. https://hooks.zapier.com/hooks/catch/123/abc)"
                    }
                }
            }'::jsonb,
            v_type_id,
            v_category_id,
            true
        );
    END IF;

END $$;
